### ISSUE TITLE
issue with _mkasset.bat

### ISSUE THREAD

**Issue by LegacyID1991** [mindbender-studio/core#109]
### Issue
if **_work_** folder is missing in the folder structure.
the **_mkasset** API is still executed but it doesn't successfully push on to the correct directory.
> ![_mkasset_bug_screencapture01](https://cloud.githubusercontent.com/assets/24475296/25234924/edbd09d6-25e3-11e7-9676-b720d7156319.gif)

currently the **_mkasset** API just checks if the folder with the same name as bat exists and if it doesn't then it creates correct folder structure underneath that asset.

### Implementation suggestion
Add another check in the _mkasset API so that it checks the complete folder structure under that asset and if it doesn't exists give the user a warning and then creates the missing part of the folder structure.

**Comment by mottosso** [comment]
Deprecated
