### ISSUE TITLE
unloading reference at maya startup

### ISSUE THREAD

**Issue by Stonegrund** [mindbender-studio/core#111]
Noticed an issue. When we opened a scene through the pipe the references didn't load. The local user had made a change in his/hers `Open Scene Options` it was set to not load references at startup. 
`Open Options-> Referencing-> Load Settings -> Load No References` . Is it possible to change this and force maya to *Load saved references load state* when opened through the pipe?

**Comment by mottosso** [comment]
Hi @Stonegrund, yes that would be possible, but I'm not sure it's intuitive. What about when the user actually wants to not load references? It can sometimes be a handy technique for loading scenes that otherwise break or crash due to any of the references.

**Comment by Stonegrund** [comment]
True. The problem was we had to research the cause of the issue. Maybe it is nothing that the pipe should force rather that we would make sure how the maya folder in myDocuments are set?

**Comment by mottosso** [comment]
Yes, best not to automate things the advanced user may want to have control over.

Best case we could add a second "Load Scene" button that doesn't provide any options but always loads references. The challenge there is deciding what exactly this button should do (who decides?) in a way that also does not create fear for the advanced user in using the standard "Load Scene" button. (Should I risk doing it "manually"?).

**Comment by mottosso** [comment]
If this issue crops up again, let's re-open this issue.
