### ISSUE TITLE
problem with reassigning lookdev

### ISSUE THREAD

**Issue by Stonegrund** [mindbender-studio/core#118]
**To recreate this issue:** 

1. Navigate to any render or lookdev task and open maya. 
2. Load asset A (model,rig,alembic or similar).
3. Load asset A lookdev.
4. Delete everything to do with asset A in `Container Manager`(aka `Show Manager`) 
5. Problem one appears. The `(lookdevDefault)` does remove the shaders in the `hypershade` but still appears in the `Cointainer Manager`

![image](https://cloud.githubusercontent.com/assets/22002943/25701437/b0d1df8a-30cc-11e7-875c-b3ade90c6420.png)

6. The `(lookdevDefault)` that still appeard in `Cointainer Manager`(even though the shaders assosiated with asset A lookdev are removed from the `hypershade` as it should) seems to create following problem.
7. Repeat step **2.** and **3.**
8. The loader imports the shaders assosiated with asset A but doesn't apply to the geometry. (See window message in image below)

![image](https://cloud.githubusercontent.com/assets/22002943/25701510/0c6f81a8-30cd-11e7-9a0f-2204e09db7bb.png)

**Comment by Sonegrund** [comment]
It was closed but this is happening again after the move to Avalon and downgrading after a custom fit.

**Comment by mottosso** [comment]
Could you elaborate on "downgrading" and "custom fit"? Which version did you downgrade from, and which version did you downgrade to? What is "custom fit"?

**Comment by mottosso** [comment]
Problem was in the config, see https://github.com/mindbender-studio/config/commit/61de0c7b6e50d38fd1fe470140e463b721165269
