### ISSUE TITLE
Restricted Access to Asset Database

### ISSUE THREAD

**Issue by mottosso** [mindbender-studio/core#133]
### Goal

Enable customised access to projects per user.

### Implementation

At the moment, everything related to any project is hosted together in a single "collection" or "table". Authentication (in MongoDB) works on a per-collection level, so we'll make projects into collections and apply ["privileges"](https://docs.mongodb.com/manual/core/collection-level-access-control/) there.

**Comment by BigRoy** [comment]
With #134 (even though locations are deprecated) are projects still each in their individual collection and as such allow customized privileges? If so, _is this implemented_?

**Comment by mottosso** [comment]
This is technically implemented, what artists do today is they use that same login to mongo, and this login have access one or more databases.

The idea is to use an artists individual email for credentials, so they share one for email and ftracj too.
