### ISSUE TITLE
help to see project/pipeline step for active maya

### ISSUE THREAD

**Issue by HenrikSkymne** [mindbender-studio/core#140]
Current pipeline often leads to having many instances of maya open.
One for model. one for rig, one for lookdev etc.

It can get confusing which maya is what at times.
Once saved or loaded you know as the path tells you, but more obvious clues would be nice.

A button that tells you what this maya is started from would be nice.
Any other way to tell this apart as well would be good.
Say different background colors for model vs rig etc.

**Comment by mottosso** [comment]
Thanks @HenrikSkymne,

Here's how they did it at another company that I found worked quite well.

![image](https://cloud.githubusercontent.com/assets/2152766/26358321/16f8328a-3fca-11e7-8679-461bd397b20e.png)

This could also be where you #107 (live context switch) via a submenu or the like.

**Comment by mottosso** [comment]
Continuing discussion in #107
