### ISSUE TITLE
Un-Select all when publish

### ISSUE THREAD

**Issue by CalleHalldin** [mindbender-studio/core#168]
**Goal**

To make selective export easier and faster.

**Motivation**
If you have a lot of assets when exporting alembic and you only need to export one of them you need to manually un-tick all of them except the one needed to be exported.
If we had the option to _unselect all_ this would become easier.

**Comment by mottosso** [comment]
You can do this already, if you click on the header of a series of instances.

Ask Henrik, he knows.
