### ISSUE TITLE
Automatic preparing of asset depening on Task

### ISSUE THREAD

**Issue by CalleHalldin** [mindbender-studio/core#169]
**Goal**

To decrees the time it takes to set-up an asset depending on what the task and also bring a gobal standard to hierarki structure.

**Motivation**
Each time for example a rigger loads a model the rigger has to do certain steps before being able to start rigging. Its same thing with everything from LookDev to modeling, they all have their own steps before the artist can either start working or publish. Since the steps are always the same that time could be better spent.

**Comment by CalleHalldin** [comment]
If this is to advance at this moment i would suggest a tool to setup a model for rigging and lookdev since this is where its needed the most.

**Comment by mottosso** [comment]
This will be solved by #83

**Comment by mottosso** [comment]
But do keep nagging me about it, I need to know which of all current issues are the most important.

I'll look towards setting up a separate priority list you can work with as well, possibly Trello.

**Comment by mottosso** [comment]
Ok, let's give this a try.

https://github.com/mindbender-studio/core/projects/1

This is the order in which I'm working, what's lacking is a motivation for delaying immediate issues, like this one, for less immediate and more time demanding issues. In a nutshell, it's to prepare you for the future. But I'll need to balance current issues with those so have a look at what I've put there and see if you can't add items yourself. You should be able to make notes as well, don't be afraid to get in there. 

This is how I know where the fire is at and what to fix or implement immediately.
