### ISSUE TITLE
Example and source code discrapency with register_family()

### ISSUE THREAD

**Issue by aardschok** [mindbender-studio/core#181]
## Issue ## 

`register_family()` data argument expects `dict`, example uses a `list`.

Code at minderbender\pipeline.py:
```python
def register_family(name, 
		    label=None, 
		    data=None,
                    help=None,
                    loader=None):
    """
    Register family and attributes for family
    Arguments:
        name (str): Name of family, e.g. mindbender.model
        label (str): Nice name for family, e.g. Model
        data (dict, optional): Additional data, see
            :func:`register_data` for docstring on members
        help (str, optional): Briefly describe this family
    """
```

Example at https://mindbender-studio.github.io/2.0/

```python
api.register_family(
    name="my.family",
    data=[
        {"key": "name", "value": "marcus", "help": "Your name"},
        {"key": "age", "value": 30, "help": "Your age"},
	])
```

## Discussion ##

Either let the function support a `list` or a `dict`. 
Personally I'd opt for a `list`.

Pros for a `list`:
- When using lists the user gets the data in the order as it is inserted; otherwise they attributes would be arbitrarily sorted. (An `OrderedDict` might also solve this.)

Cons for a `list`:
- The same key can be used multiple times, overwriting any previous values of that key. So this would be something we'd need to check for.

**Comment by mottosso** [comment]
Thanks for this @aardschok, the registration of families is actually being superseded by Creator Plug-ins (#157).

This to me also highlights a need for Sphinx Documentation (#28), such that code and documentation never go out of date.
