### ISSUE TITLE
Light Rig

### ISSUE THREAD

**Issue by LegacyID1991** [mindbender-studio/core#33]
_For the lighting department:_

**Aim:**
New Family to add, not yet decided but for now called light rig or light-rig
New Family for the asset creator
New Family for the asset loader

The idea is to implement a workflow for lighters and render artists so that they can export lighting setups called light-rigs so that the same setup can be imported and used across multiple shots of a project and also saved for later use such as turntables or demos.
![capture150](https://cloud.githubusercontent.com/assets/24475296/22416809/fc8c8380-e6d0-11e6-8a1a-eff2801384ef.PNG)
![capture151_edit](https://cloud.githubusercontent.com/assets/24475296/22419394/8ec0c548-e6dd-11e6-892c-c3334447872b.PNG)

**What is needed.**

- add family
- add new maya "set"
- add scheme update
- research if lights for different render engines will become a issue for instance collector
- add new collector 
- add new validators
- add new extractors
- add functions if needed

**Digration**.
This is for now meant to be only on maya hosts and not all apps. (Reasons being that maya is the only app we use today for lighting) If this can be created to be future proof and to work across different hosts then that would be great.
Prio is for now to get it to work for Octane first, followd by Redshift, then mental ray

**Comment by mottosso** [comment]
Consider whether there is any difference between a Light-Rig and Rig. There might be dedicated validation and export, if so it could be helpful to list those differences. Otherwise a normal rig may work, as the exported file is in Maya's own format (`.ma`) it would take into account lights as well.

On a cosmetic note, consider using only one word separator - CamelCase, mixedCase, snake_case or dash-case. E.g. `LightRig` or `light-rig` rather than `Light-Rig`. At the moment, there are two separators being used at once, which can be superfluous.

**Comment by LegacyID1991** [comment]
cosmetic note taken.
Will try and unlearn that bad habit and try and remember to be more concise.

**Comment by LegacyID1991** [comment]
so the _LightRig_ could use all the pipeline.py commands that normal _Rig_ does. 
just a diffrent family and name ?

**Comment by mottosso** [comment]
Try making a rig in Maya for lights using the Rig family. The things you find that differs from normal chatacter rigs are the things you would make a new family, such as LightRig, for.

A new family would allow you to dedicate unique plugins to it, but at the same time increase complexity for you the maintainer.

In general, the fewer families you have, the less work there is for you to maintain and customise.

**Comment by mottosso** [comment]
Did you get anywhere with this?

**Comment by mottosso** [comment]
Feel free to re-open should the issue appear again.
