### ISSUE TITLE
Pyblish still thinks deleted container manager is up for publishing

### ISSUE THREAD

**Issue by LegacyID1991** [mindbender-studio/core#34]
> "Managern deletar referensen i reference editorn men referensen finns fortfarnade i managern och pyblish tror fortfarnade att asset finns kvar. Antagligen pga att "Asset set" inte deletas."

**Process to find bug:**
_When working with the container manager:_
- _You load a asset into a scene_
- _Then you want to delete the asset from the scene._
- _Deleting it from the manager does the job for the reference editor._
- _The asset is still present in the manager window_
- _Open up the publishing window_
- _The asset is there as well_

**Comment by LegacyID1991** [comment]
Solution could be that the asset manager doesn't delete the maya sets for the asset.

**Comment by mottosso** [comment]
This this apply to assets other than Rigs?

Have a look at updating the Collector for this. Basically, if an instance is empty, maybe not collect it.

The "problem" is that an Instance is created for the rig, but isn't technically part of the rig. So when you go ahead and delete the rig, the Instance would still remain and get picked up by the Collector.

**Comment by LegacyID1991** [comment]
So I am back on this.

**Comment by LegacyID1991** [comment]
I will return to this one during the weekend or next week,
I am currently working on better info about what goes wrong in this issue.
