### ISSUE TITLE
Alembic import sets timeline in maya

### ISSUE THREAD

**Issue by LegacyID1991** [mindbender-studio/core#35]
**Disclaimer**
This is not a feature request

> "Import alembic updaterar inte timelinen."

Does the asset loader change settings in maya when an asset is loaded?

Example would it change the timeline _IN_ and _OUT_

**Comment by mottosso** [comment]
I should have mentioned; the time range for alembic caches comes from user-defined attributes in Maya on the Instance, e.g. `MyCharacter01_SET`.

It should have a start and end frame attribute, which comes from the current Maya timeline at the time of creating it. The export will use this attribute, as you can see in the Alembic extractor plug-in.

**Comment by LegacyID1991** [comment]
I dont think we need to use that in the importer.

why dont we set the _IN_ and _OUT_ as we set _FPS_ in _.bat_ files ?

we could have it be both a startup thing for every app and do a _global validator_ for pyblish to check the env variable

wouldn't that be easier ?

**Comment by mottosso** [comment]
Yes, go for it.

What I would do is have both. The environment variable represents a global value, whereas the attribute in Maya can be used to override it by the artist.

I would expect there to be a need to do things like that on a regular basis, both for making quick changes, but also for things like adding pre and post roll to individual shots and characters.

To implement that, you could set the environment variable in the bat file and read it from the extractor, but only if the Maya attribute has not been set.

At the moment the attribute is set automatically in the registration of the family in the pipeline.py of Maya. If you default this to an empty value, the artist could use this to override the environment variable.

Let me know if that makes sense!

**Comment by LegacyID1991** [comment]
I think that for now everything should be set by the bat file, 
and should be validated before publish so that the user hasn't changed their settings by mistake.
It might create problems with that the user has to go to the bat file and change the value if they know the bat file to be incorrect but at least that creates a level of control that I think right now the supervisors wants.

**Comment by mottosso** [comment]
I just noticed I had misunderstood the initial question; that when importing an Alembic, the Maya timeline is set.

Have a look at the animation loader for this. You can either remove it, or implement logic to only do it under special circumstances (e.g. only once, only when timeline is at a default value, only within the first 5 minutes of launching Maya).

The answer I gave above relates to exporting Alembic.

**Comment by mottosso** [comment]
If this is still a problem, feel free to re-open this thread.
