### ISSUE TITLE
Container Manager doesn't change version on loaded camera

### ISSUE THREAD

**Issue by LegacyID1991** [mindbender-studio/core#36]
> "Kameran kan inte upgrade/downgrade
![kamera](https://cloud.githubusercontent.com/assets/24475296/22460673/420a14ba-e7a6-11e6-90f3-daa5b8a739e1.jpg)
Kamera exporterades inte med animation fören jag slog på "shake", Ska undersöka lite mer på denna."

**Process to get to bug:**
_When working with the container manager_

- _Open new scene with already published assets_
- _Load the shot camera_
- _open the container manager_
- _cameras versions are visible_
- _camera version cannot be changed neither up nor down_

**Comment by mottosso** [comment]
Try not to add `bug` etc. in the title, that's what labels are for. At the moment, you don't have write permissions to this project (to avoid accidental pushes) and can't add labels yourself, but I'll manage labels till then.

**Comment by mottosso** [comment]
This might be an issue with the Alembic export. Have a look a the Alembic exporter, and see if there are any options for Cameras in the Maya documentation you need to add. Alternatively, have a look at your previous alembic exporter, and see what flags were passed when exporting cameras.

**Comment by LegacyID1991** [comment]
That was why I added the labels in the titles. But I will stop doing so if it is annoying. :)

**Comment by mottosso** [comment]
No problem. :) A minor thing that I expect you to find elsewhere on GitHub
and other places, it's good to stay consistent.

**Comment by mottosso** [comment]
Is this still a problem?

**Comment by LegacyID1991** [comment]
I will start investigating this again, tonight

**Comment by LegacyID1991** [comment]
This is the Error message I get:
Program error: Unsupported representation: {u'path': u'{dirname}/CameraRig{format}', u'schema': u'mindbender-core:representation-1.0', u'format': u'.abc'}

**Comment by LegacyID1991** [comment]
I ran this code two times to publish two cameras:
```
cmds.file(new=True, force=True)

from maya import cmds
from mindbender import maya, api


camera = cmds.camera(name="studioCamera_RIG")
cmds.select(camera)
assembly = cmds.group(name="ROOT")
cmds.select(camera)
transform = cmds.ls(selection=True, type="transform")

startTime = cmds.playbackOptions( query=True, minTime=True)
endTime = cmds.playbackOptions( query=True, maxTime=True)

halfTime = (((endTime-startTime)/2)+startTime)


cmds.cutKey( transform, time=(startTime, endTime), attribute="ty" )

cmds.setKeyframe(transform, time=startTime, attribute="ty", value=0)
cmds.setKeyframe(transform, time=halfTime, attribute="ty", value=1)
cmds.setKeyframe(transform, time=endTime, attribute="ty", value=0)

cmds.select(assembly)

container = maya.create(
    "CameraRig",
    family="mindbender.animation",
    options={"useSelection": True}
)

cmds.file(rename="temp.ma")
cmds.file(save=True)

from pyblish import util
util.publish()
```

I then proceeded to try and load the camera, it worked to load the latest publish but when trying to downgrade I got into above error message

**Comment by LegacyID1991** [comment]
After some research on [help.autodesk.com](http://help.autodesk.com/view/MAYAUL/2016/ENU/?guid=GUID-854D22F6-7547-465C-8A13-E21A8A6D9714)
I cannot find a link between our exporter and this problem, there are not any _flags_ specifically about exporting cameras.
And after researching our old alembic exporter I cannot find any extra flag except for the write worldspace flag, but that doesn't seam to be linked to our issue .

That is as far as I will get today, I will return to this issue again.

@mottosso Do you see something I don't ?

**Comment by mottosso** [comment]
I'll try and take a look in the afternoon.

**Comment by mottosso** [comment]
Discovered two related issues.

1. You cannot publish a camera rig, how are you using and animating cameras today?
2. An error appears on trying to save a scene with a camera. An `mbID` is trying to get added but cannot. You should have been seeing errors on each save with cameras.
