### ISSUE TITLE
Can mindbender ID validator be optional?

### ISSUE THREAD

**Issue by LegacyID1991** [mindbender-studio/core#38]
Animatic artist want to know if we can make some of **the validators that checks not so important stuff** can be optional, when they work, they create a lot of _"dummy geo"_ that they want to be exported so that animators have something to start with.

**Comment by mottosso** [comment]
I put together a possible solution to this recently, something that adds ids automatically to all new meshes. I'll put together a PR once I'm back home.

**Comment by mottosso** [comment]
Should should be resolved with the new [automatic IDs](https://github.com/mindbender-studio/core/pull/40).
