### ISSUE TITLE
LookDev transfer Error

### ISSUE THREAD

**Issue by CalleHalldin** [mindbender-studio/core#42]
[Example move](https://drive.google.com/file/d/0B7RmZ_BoQHNeMmRSQm43RWozWjQ/view?usp=sharing)
Process to get to produce the bug:

- Create a model for _assetA_.
- Create a lookDev for _assetA_.
- Create model _assetB_.
- Create lookDev for _assetB_.
- Load _ModelA_ and Lookdev into a new scene
- Load _ModelB_ and Lookdev into same scene
- Load Lookdev for _ModelA_ again and it will get the _ModelB_ lookDev and it can't be changed back with the loader.

Seems like its always the First models and lookDev that you load that transfers the shader to the wrong asset. As can be seen in the video even though I create a completely new scene the bug is still there.

**Comment by mottosso** [comment]
Thanks @CalleHalldin, having a look at this tomorrow morning. Make sure the steps to reproduce does reproduce the problem, that way it'll be much quicker to fix.

**Comment by mottosso** [comment]
Sorry I haven't gotten into this yet.

@LegacyID1991, you might be able to dive into this. The problem must be somewhere in the loader for this family, see [here](https://github.com/mindbender-studio/core/blob/master/mindbender/maya/loaders/mindbender_look.py).

I would start printing things, and see if you can pinpoint where in the loader the problem occurs. Likely in the `maya.apply_shaders` function. If you print the [`relationships`](https://github.com/mindbender-studio/core/blob/e95bc7655bc37ebf75d09a5fb76cf42d27b9d9c8/mindbender/maya/loaders/mindbender_look.py#L52) variable, it'll give you a dictionary. You can use that dictionary to manually call `apply_shaders` and debug from there.

**Comment by mottosso** [comment]
@LegacyID1991 Did you have a look at this? If not, let me know here so I know whether I should look at it.

**Comment by LegacyID1991** [comment]
I am sorry to say that I have been so slammed with other work duties that I haven't gotten to this one yet.

**Comment by mottosso** [comment]
That's ok, I just need to know whether I should look into it so we don't work on it at the same time. Would you like me to take over?

**Comment by LegacyID1991** [comment]
go right ahead.
😄

**Comment by mottosso** [comment]
Ok, I've found the problem.

The problem is that it assigns to meshes based on the name of the shader group, but if the shader group has the same name in both look dev publishes, such as `blinn1SG`, the it gets confused and assigns the wrong one.

Putting together a fix now.

**Comment by mottosso** [comment]
Fixed, @LegacyID1991 is updating the pipeline shortly.
