### ISSUE TITLE
Have clone special tool connect visibility

### ISSUE THREAD

**Issue by CalleHalldin** [mindbender-studio/core#43]
On the current rig where we have different hair styles, noes, etc that is connected with visibility driven by an attribute on the rig,
e.g. Attribute _Woman01_ has a setdriven connection to visibility to a group containing the meshes for _Woman01, groups for other variations like _Man01_ are turned off.

The issue we noticed is that the out mesh created with the "clone special" tool does not get these visibility connection from the rigged mesh so alembics will not record these changes when exporting.

**Update** We need a a new Clone (special) tool that connects the visibility but also to keep the old one since we don't want visibility to be connected from the model reference to the rigged mesh only from the rigged mesh to the Out mesh.

**Comment by CalleHalldin** [comment]
Side question that relates, can we group the cloned meshes freely inside the OUT group if we wanted to hock up the visibility between the groups manually?

**Comment by mottosso** [comment]
@LegacyID1991 this can be implemented [here](https://github.com/mindbender-studio/core/blob/5d076e60f292805fef98f7d675fccaaae6480140/mindbender/maya/interactive.py#L104).

This is where currently *all* user-defined attributed are added to a new clone. What you'll need to do is to simply include `.visibility` there as well.

**Comment by mottosso** [comment]
> Side question that relates, can we group the cloned meshes freely inside the OUT group if we wanted to hock up the visibility between the groups manually?

Better make this a separate issue with a more thorough description and something I can reproduce. Not sure I'm understanding what you mean.

**Comment by LegacyID1991** [comment]
This issue needs to be updated
as of now I am not working on this.

**Comment by mottosso** [comment]
Updated with what? I've assigned it to you to indicate that it's up your alley. You are free to implement it whenever you find the time.

**Comment by LegacyID1991** [comment]
I have talked with @CalleHalldin about this feature and after that I felt that this issue needed to be updated.

**Comment by mottosso** [comment]
Sorry, can you be more specific? Is there something you would like to add, should I close it or is someone else working on it?

**Comment by LegacyID1991** [comment]
Leave it open, Calle will either edit this issue or I will complete it and refer to it with my solution.
