### ISSUE TITLE
Launcher GUI

### ISSUE THREAD

**Issue by mottosso** [mindbender-studio/core#61]
### Goal

- Simplify entering assets for artists
- Simplify creating assets for supervisors
- Enable implementation of #25 and #31
- Notify local power users (e.g. Arvid) of updates to mindbender-core
- Notify remote users of updates to mindbender-setup

### Implementation

The GUI should feature a method of choosing (1) project, (2) asset and (3) app along with the ability to create new (1) projects and (2) assets.

```bash
 ___________________________________________
|                                        _ x|
|___________________________________________|
|project1      |assets| shots|app1          |
|project2      |______|______|app2          |
|...           |asset1       |...           |
|              |asset2       |              |
|              |...          |              |
|              |             |              |
|              |             |              |
|              |             |              |
|_____________+|____________+|______________|
```

It should also facilitate editing of projects and assets, such as frame rate and start/end frame, similar to the Attribute Editor of Maya.

```bash
 _____________________________________________________________
|                                                          _ x|
|_____________________________________________________________|
|project1      |assets| shots|app1        |key    value       |
|project2      |______|______|app2        |key    value       |
|...           |asset1       |...         |..     ...         |
|              |asset2       |            |                   |
|              |...          |            |                   |
|              |             |            |                   |
|              |             |            |                   |
|              |             |            |                   |
|______________|_____________|____________|___________________|
```

**Comment by mottosso** [comment]
Occurred to me that we will also want to specify task in here.

```bash
 _____________________________________________________
|                                                  _ x|
|_____________________________________________________|
|project1      |assets| shots|task1        |app1      |
|project2      |______|______|task2        |app2      |
|...           |asset1       |...          |...       |
|              |asset2       |             |          |
|              |...          |             |          |
|              |             |             |          |
|              |             |             |          |
|              |             |             |          |
|_____________+|____________+|_____________|__________|
```

**Comment by mottosso** [comment]
Some inspiration, Colorbleed has got this going for similar purposes.

![image](https://cloud.githubusercontent.com/assets/2152766/23507616/d729e6c2-ff45-11e6-8399-79c9b200530b.png)

**Comment by mottosso** [comment]
We'll also want to keep an eye on launched processes and their terminals. Such as via a separate page listing each started subprocess and its associated standard out and error.

**Comment by tws0002** [comment]
is this explorer example going to share with us ?

**Comment by mottosso** [comment]
Hi @tws0002, the example is courtesy of @BigRoy. I would inquire with him.

Our goal is similar, and it will be included in this project. See #67 for updates.

**Comment by tws0002** [comment]
this feature is very user-friendly!! can't wait to use in our production pipeline. this UI will replace the cmd launcher function?

**Comment by mottosso** [comment]
> this UI will replace the cmd launcher function?

Yes, that's right.

**Comment by CalleHalldin** [comment]
Seems like Colorbleed has moved away from individual "Workplace" files?

**Comment by mottosso** [comment]
> Seems like Colorbleed has moved away from individual "Workplace" files?

It's possible, or the browser might not be showing all folders.

This is one great benefit of taking control over the way in which artists browse. You are free to customise it to only show things relevant to a particular user. For example hiding things, like the user directory in this case, or protected files - such as other projects - or irrelevant things - like rigs when working on modeling.

**Comment by CalleHalldin** [comment]
They way they have it looks pretty much perfect to me, a simple list where you can find the latest working file (if its the case) and the ability to open it. This something to consider for the future before we continue to far on the current setup. or maybe as you said this can be done just visually in the launcher.
Right now on the current project you constantly have to check all "Working folders" to find the latest file and there are sometimes 3 or more of them which becomes time consuming and frankly annoying.
it also feels like this way can cause mistakes where you accidentally open up a version that is the latest because you simply missed it or different users naming convention confuses you, which kinda defeats the purpose of a pipeline. 
In an ideal world one artist works on one assets for the specific task until its done but that rarely happens in the land of commercials or other fast moving productions, things can be very dynamic. At least at our company.

**Comment by mottosso** [comment]
Do you mean that this..

```bash
Bruce/work/modeling/calle/maya/...
```

Should become this..

```bash
Bruce/work/modeling/maya/...
```

Such that working files from all artists are stored together?

**Comment by mottosso** [comment]
Let's pop up a separate issue about the reorganisation of work files, let's focus this issue on the Launcher look and functionality.

Here's some more inspiration and what I'm going for, from a project I developed a few years ago.

(Click to show full resolution).

![untitled project](https://cloud.githubusercontent.com/assets/2152766/23545036/7a2dd2b0-fff1-11e6-8802-2566ac14443f.gif)

**Comment by CalleHalldin** [comment]
alright lets do a separate issue, but yeah otherwise i like it!

**Comment by mottosso** [comment]
> alright lets do a separate issue, but yeah otherwise i like it!

Can you create this issue, please?

**Comment by CalleHalldin** [comment]
Doing it!

**Comment by tws0002** [comment]
Hi mottosso I wanna share some good stuff with u guys here is a VFX & Animation Pipeline Library created by eoyilmaz (https://github.com/eoyilmaz) it call anima (https://github.com/eoyilmaz/anima) and stalker(https://github.com/eoyilmaz/stalker). is a vfx Production Asset Management System. here is some info about this tools http://vfx.animaistanbul.com/stalker_home/.

**Comment by mottosso** [comment]
Thanks, I'm familiar with Erkan's work. For production tracking - tasks, dates, assignments etc - I would also make this recommendation, but do you mean it offers and alternative to this Launcher?

**Comment by tws0002** [comment]
For what i know about anima manager it can be assign task base on artist. when you start anima manager it need a user login to filter each user work task only. wich I think is very useful when you have a big scale project. 
What i think is can mindbender launcher have this function?

**Comment by mottosso** [comment]
> What i think is can mindbender launcher have this function?

Yes, though it isn't a priority at the moment.

For that to happen, we would first need task management - like Stalker, Shotgun or Ftrack - which isn't present at Mindbender yet, but will be in the future. All that this Launcher does, will be built with this in mind.

**Comment by tws0002** [comment]
Thanks for your clear explain.
how can i test the current version of MB Luancher?

**Comment by mottosso** [comment]
> how can i test the current version of MB Luancher?

At the moment, I wouldn't recommend it. If you [subscribe to the PR](https://github.com/mindbender-studio/launcher/pull/1), you'll know when development continues.

**Comment by tws0002** [comment]
ok got it. Thank you

**Comment by jadecilcleton** [comment]
Hello Marcus, 
Sorry I didn't see this git discussion before.
Colorbleed reference is really nice. For the UI I also have this wireframe as suggestion:

![image](https://cloud.githubusercontent.com/assets/27027693/24818434/f6a30b2c-1bb6-11e7-96db-b6e02be5e3d0.png)

We can talk about this on next week also.

**Comment by mottosso** [comment]
Hey @jadecilcleton, thanks for the wireframe.. who are you? :)

**Comment by jadecilcleton** [comment]
Hahaha Hey Marcus,

I´m Bruno Hamzagic from Mindbender crew. Nice to Have this channel to organize all suggestions :)

**Comment by mottosso** [comment]
Aah, hey Bruno. :) Heard you were flying in next week? Looking forward to meeting you.

And yeah, this would be where all practical, development suggestions and discussions would be held, where they can be arranged, assigned and completed under version control. Good to see you're enjoying it so far.

**Comment by mottosso** [comment]
Implemented.

https://github.com/mindbender-studio/launcher
