### ISSUE TITLE
Include history and connections with lookdev assets

### ISSUE THREAD

**Issue by Stonegrund** [mindbender-studio/core#69]
At the moment lookdev only publishes shadingGroups.

Octane has problem with sss and displace, it brakes each other. Solution rightnow is to apply an iDisplace, which is a mesh texture displace deformer (iDeform plugin). 

This is the workflow at the moment:
-Import desired defaultMesh.
-CloneSpecial.
-Polysmooth all cloned meshes. (Deformer nr1, needed for iDisplace to have enough poly to displace as accurate as possible)
-iDisplace (deformer nr2)

Wish: Deformers that are assigned to specific mesh in lookdev scene also gets published and assigned when loaded into render scene assembly such as the materials. 

Is this possible?

FYI: The order of Polysmooth and iDisplace are important. Also as a note is that is it possible to have one iDeform and connect it to several meshes, while the polysmooth is only per mesh assignable. It would of been nice to have one polymesh operation which has several meshes attached to it as well.

**Comment by mottosso** [comment]
Hi @Stonegrund,

Would it be acceptable to include these deformers in the original model? If you publish your model as a rig, and maybe call it `modelDeformed` or such so you can recognise it, then deformers will come along with it. You'll need `out_SET` and `controls_SET`, but those can be empty for now.

If that works, we can have a look at a new family, such as `historyModel` or such that includes history.

**Comment by Stonegrund** [comment]
Will this follow the alembic? 

It would not work because a displacement map is plugged in to iDisplace node. 

Since we polysmooth the mesh a lot, the mesh and scene gets heavy. The plan is to turn it on only at time of render.

**Comment by mottosso** [comment]
Does the `iDisplace` node already exist in the lookdev scene? Does it come along when you publish?

If so, would it be acceptable to automatically connect the mesh to this node?

**Comment by mottosso** [comment]
Are you familiar with the `smoothMesh` output? The one you see press 3 on your keyboard.

**Comment by Stonegrund** [comment]
iDisplace does not come along with the publish. Yes both mesh smooth and iDisplace are created in the lookdev scene. 

If iDisplace node is put inside the lookdevDefault_SET, the evaluator gets angry. See attached image 
![2017-03-03 12_48_15-pyblish](https://cloud.githubusercontent.com/assets/22002943/23550129/c232c1ce-000f-11e7-9736-109c58addc78.png)

**Comment by Stonegrund** [comment]
Yes, I am familiar to this but iDisplace ignores this type of operation. 

It would be super helpful if at least the iDisplace deformer gets published and gets applied when lookdevDefault_SET gets loaded in. The only problem then is to rearrange the order of polysmoot operation and the iDisplace operation. 

Most of the objects will more or less have the same subdivisions in the polysmooth operation. But it changes from model to model in the iDisplace.

**Comment by mottosso** [comment]
> It would be super helpful if at least the iDisplace deformer gets published and gets applied when lookdevDefault_SET gets loaded in. The only problem then is to rearrange the order of polysmoot operation and the iDisplace operation.

This is possible.

We can include nodes of this type with the publish, and then connect arbitrary attributes. In this case, we can bypass the `polySmooth` by connecting the `smoothMesh` from the shape node into `iDisplace`. `smoothMesh` is a built-in `polySmooth` with every mesh.

So what we have then is two subsets, A and B, a model and a lookdev. Upon load, we with to make connections from A to B. In this case, from `A|someMesh.smoothMesh` to `B|iDisplace.input`.

How would you like to specify this relationship? We could try and automatically deduce the connections from the lookdev working scene, and store those alongside the published shaders.

Thoughts?

**Comment by mottosso** [comment]
As an alternative to `smoothMesh`, we could include your `polySmooth` in the lookdev publish as well, and connect the mesh to that.

**Comment by Stonegrund** [comment]
> smoothMesh is a built-in polySmooth with every mesh.

I will have to look further to make this work with the` iDisplace` if we choose to do it this way.

> As an alternative to smoothMesh, we could include your polySmooth in the lookdev publish as well, and connect the mesh to that.

That sounds great. I would prefer this. I mean as long as they recognize the `MB ID`, since object names tend to change name when `Clone (Special)` is used.

**Comment by mottosso** [comment]
> I will have to look further to make this work with theiDisplace if we choose to do it this way.

Have a look at the input to iDisplace when it's connected. It should have the `outMesh` attribute of a mesh connected to one of its inputs. If you break this and manually connect `smoothMesh` you should find that nothing has changed.

Then in the attribute editor for the mesh, under the Smooth Mesh tab, you can adjust the iterations, like with `polySmooth`.

**Comment by Stonegrund** [comment]
> Have a look at the input to iDisplace when it's connected. It should have the outMesh attribute of a mesh connected to one of its inputs. If you break this and manually connect smoothMesh you should find that nothing has changed.

I am not sure about this. But yes it has a outPutGeometry and inMesh when I disconnect this it is like removing the history and when I connect them again it is possible to modify again. 

> Then in the attribute editor for the mesh, under the Smooth Mesh tab, you can adjust the iterations, like with polySmooth.

Yes yes, but it seems it is only for preview purposes. If I have `iDisplace` connected to a `mesh` the surface does not displace even if I change iterations. 

I have to first assign a  `Mesh -> Smooth` then `iDeform -> iDisplace` to make it work.

**Comment by mottosso** [comment]
> Yes yes, but it seems it is only for preview purposes.

Try this, replace `myMeshShape` with the name of your mesh shape, and `iDisplace1` with the name of the `iDisplace` node.

```python
from maya import cmds
mesh = "myMeshShape"
idisplace = "iDisplace1"
cmds.connectAttr(mesh + ".outSmoothMesh", idisplace + ".inMesh", force=True)
```

Pressing 3 on your keyboard will now not only work for preview, but also increase the smooth iterations of the mesh passed to your `iDisplace` node.

**Comment by Stonegrund** [comment]
It feels like I am doing it wrong -.-
![2017-03-03 14_08_58-outliner](https://cloud.githubusercontent.com/assets/22002943/23552212/fd59be14-001a-11e7-9f86-dafc4303a3ed.png)

**Comment by Stonegrund** [comment]
> Pressing 3 on your keyboard will now not only work for preview, but also increase the smooth iterations of the mesh passed to your iDisplace node.

Then I must be missing something. Hmm...

**Comment by mottosso** [comment]
It looks like `iDisplace` doesn't have the attribute `inMesh`.

If you leave it connected, and graph the connections into `iDisplace1`, where does the mesh plug into?

You know what, this isn't important. We can do `polySmooth` too and optimise later.

For @LegacyID1991, here's what we need to do.

1. On publish, we need to inspect the connections made from shaded meshes to published nodes, and record them into a dictionary. For example `{"mesh1.outMesh": "iDisplace1.inMesh"}`. We'll then include this in the metadata of the publish.
2. On load, we load this metadata and make the connections as recorded.

That should do it!

**Comment by Stonegrund** [comment]
@LegacyID1991 It would be nice if we can do this as soon as possible.
