### ISSUE TITLE
Reload reference issue in render scene

### ISSUE THREAD

**Issue by Stonegrund** [mindbender-studio/core#76]
When I open a `saved` `render scene`, the scene is empty. The folders are there, and the `references` are referenced in, but I have to `reload` the `references` to make them appear in the scene.

**Comment by mottosso** [comment]
Can't tell what this is. Could you post instructions for how I could reproduce this on my end?

For example..

1. New scene
2. Load A, B and C
3. Save
4. Re-open saved scene
5. Broken

**Comment by Stonegrund** [comment]
1 New scene (`...film -> sh010 -> maya render`)
2 Open a `master_render_scene`. That contains lights and render settings and so on.  
3 Load content from `sh010`
4 Save
5 Re-Open saved scene (`...film -> sh010 -> maya render` work scene)
6 Broken 

In the picture below, the yellow marked assets. They seem to be referenced but the folders are in the outliner.
![2017-03-06 16_44_53-outliner](https://cloud.githubusercontent.com/assets/22002943/23617159/6d3375d6-028c-11e7-8c1f-7f35a48fffcf.jpg)

**Comment by mottosso** [comment]
Could you confirm whether your `AbcImport.mll` plug-in is auto loaded? It'd be under Window -> Settings -> Plug-in Manager. By the time you open the scene, this plug-ins should already be loaded, but might not be.

**Comment by Stonegrund** [comment]
Sadly it is loaded and auto loaded. In both scenes.

**Comment by mottosso** [comment]
Ok. Does it happen with anything but Alembic files? Are the lookdev shaders present, or do you need to reload those as well?

**Comment by Stonegrund** [comment]
No! It seems only the `alembic`. The good thing is that even after I have to reload, all of the changes I have done is still present. Like the `defaultLookdev` I import. Nothing but the `alembic` in the reference editor seems to be the issue. 
Also, it doesn't work to `rightklick -> reference -> reload reference` doesn't work. I have to reload it with the button next to the `Unresolved name: ` box.

**Comment by mottosso** [comment]
Ok, that narrows it down a bit. Sounds like a Maya issue. Having a look.

**Comment by BigRoy** [comment]
When testing this ensure the plug-in was loaded prior to opening the scene! That should remove this issue. To have this correctly functional upon Maya launch (and directly opening a scene file) add these to your `userSetup.py` to have Alembic force loaded before the scene is opened (autoload doesn't suffice unfortunately):

```python
try:
    import maya.cmds
    maya.cmds.loadPlugin("AbcImport.mll", quiet=True)
    maya.cmds.loadPlugin("AbcExport.mll", quiet=True)
except (ImportError, RuntimeError) as e:
    print(e)
```

**Comment by mottosso** [comment]
Pushing a fix with this now, thanks Roy.
