### ISSUE TITLE
Disappearing mesh at render

### ISSUE THREAD

**Issue by Stonegrund** [mindbender-studio/core#85]
- Importing `alembic` and importing `historylookdevDefault`
- Render looks good so far.
- Selecting `alembic` reference node and then the `lookdev` reference node and using `auto connect`
- Assets move to their place as expected but as render is invisible. 

Not happening to all meshes. Have not yet found any difference on the disappearing assets.

**Comment by mottosso** [comment]
Thanks @Stonegrund,

Could you confirm that the meshes still disappear when you have imported the references in the scene? My suspicion is that your renderer may have trouble with the Alembic node in combination with references.

**Comment by Stonegrund** [comment]
Yes, alembic is both loaded and visible. The loaded `historylookdevDefault` asset gets bugged only after use of  `auto connect`  tool. Until then it is visible in render, but is in origin of the scene obviously.

**Comment by mottosso** [comment]
Ok, to confirm, in the File -> Reference Editor, all references are imported? As in, there are no references in the scene at all?

**Comment by Stonegrund** [comment]
Got some more specifics on the bug. 

Fist an answer to your question. All of the references are loaded, but not directly imported to the scene, they are still as references. 

However, this is what I do to recreate the issue. 
1.Loading alembic ex. tree
2.Loading historylookdevDefault ex.tree
3. Selecting first alembic then the lookdev in outliner and using `auto connect `. Tree asset pops to place and renders without problem, as expected.
4. Importing the tree historylookdevDefault asset again. BOOM, the first loaded trees are now invisible to the render, however, they all move to their places.

FYI: One tree asset contains 3 tree meshes, instead of duplicating, the animator loads in another tree asset with 3 trees.

**Comment by mottosso** [comment]
> Fist an answer to your question. All of the references are loaded, but not directly imported to the scene, they are still as references.

Ok, can you try importing all the references in the File -> Reference Editor and see whether the problem persists.

**Comment by Stonegrund** [comment]
Also, we looked at the inMesh from the historylookdevDefault and that is visable to the camera in rendering. It seems to be something going on with the outMesh from the historylookdevDefault. 

Again, this is only for the assets we load in more than once.

**Comment by Stonegrund** [comment]
> Ok, can you try importing all the references in the File -> Reference Editor and see whether the problem persists.

Sure I'll try this right away

**Comment by Stonegrund** [comment]
It does not work to import the alembic nor the historylookdevDefault. In previous attempt on hidden object is seems that the visibility connection gets broken :/

**Comment by mottosso** [comment]
Ok, sorry if this is pedantic, but there's some ambiguity to your description.

> It does not work to import the alembic nor the historylookdevDefault.

Do you mean you could not import the references, or that when you imported the references the problem persisted?

> In previous attempt on hidden object is seems that the visibility connection gets broken :/

Can you make another 1-2-3 breakdown of how I can reproduce this?

I've attempted to reproduce your problem locally, but could not. Could it be based on your specific renderer? Does the problem persist with another renderer, such as Maya Software?

**Comment by Stonegrund** [comment]
No I am sorry not making it clear enough. I will try to be more detailed. 

`Do you mean you could not import the references, or that when you imported the references the problem persisted?`

I can import references but it doesn't make a difference, the invisible assets are still invisible. File->Reference Editor ->Right klick on reference-> File -> Import Objects From Reference.

I ment that I tried to import alembic first=no change and then also tested to import the historylookdevDefault=no change

`Can you make another 1-2-3 breakdown of how I can reproduce this?`
1.Loading alembic ex. `cube1` and `sphere1` (lets say sphere1 is hidden in animation for few frames)
2.Loading historylookdevDefault ex.`cube1` and `sphere1`
3. Selecting first alembic then the lookdev in outliner and using auto connect. The assets pops to place and renders without problem, as expected. And the hidden `sphere1` is still hidden. 
4. When I import alembic: File->Reference Editor ->Right klick on reference-> File -> Import Objects From Reference = no change
5. When I import historylookdevDefault : File->Reference Editor ->Right klick on reference-> File -> Import Objects From Reference = no change BUT
6. Saving the scene.
7. Opening the scene and the hidden `sphere1` is now visable. Connection broken?

**Comment by Stonegrund** [comment]
The problem also seems to be apparent in Octane renderer.

**Comment by mottosso** [comment]
Ok, in this case, I would try and reproduce the problem without the pipeline, by exporting alembics manually and referencing them manually. Then I would get in touch with Octane support about it and send them either the scene or 1-2-3 on how to reproduce it.

Closing this, feel free to re-open if Octane can't help.
