### ISSUE TITLE
Publish source file using native format

### ISSUE THREAD

**Issue by mottosso** [mindbender-studio/core#87]
### Goal

Enable publish of source file from Maya with unknown nodes present.

### Motivation

At the moment, source files are always exported as `mayaAscii`, but when the artist has previously saved his scene using `mayaBinary` then the conversion of unknown nodes cannot be made and the publish fails.

### Implementation

Match the source file with the format in which the artist has saved his file.

**Comment by BigRoy** [comment]
The other way to think about this is to avoid having unknown nodes in the scene. Or is that unmanageable?

**Comment by mottosso** [comment]
It might not be feasible, as some artists work with software that others won't have access to. In this case Octane.

If in a native format, those artists could still open those scene and even save it, without breaking any of the unknown nodes.

**Comment by BigRoy** [comment]
> It might not be feasible, as some artists work with software that others won't have access to. In this case Octane.

Makes sense!

**Comment by mottosso** [comment]
Of course, it's debatable whether artists working with Octane *should* leak Maya scene files to artists without access to it. In an ideal world this would never happen. 

In reality it might be difficult to avoid, but there is real danger as many have already experienced with [the dreaded Turtle nodes](http://mayafeedback.autodesk.com/forums/160518-small-annoying-things-to-fix-in-maya-forum/suggestions/6571515-kill-the-turtle) lingering around.

**Comment by mottosso** [comment]
Source files were discarded in favour of linking to the original files directly via the Loader. (Not yet implemented).

The difficulty in exporting the original source file is that internal links to work-folder related things are broken, making it pretty much useless beyond being just a backup, which happens separately anyway.
