### ISSUE TITLE
Can i start MB pipeline hooked with software without using MB.bat process?

### ISSUE THREAD

**Issue by tws0002** [mindbender-studio/core#89]
I just wonder, can I start MB pipeline hooked with software without using MB.bat process?

**Comment by mottosso** [comment]
`mb.bat` does exactly 2 things.

1. Set environment variables
2. Launch an application

You can (1) manually, you just got to know what variables to set.

The best way to find out is to enter a project with `mb.bat` and query the variables it set for you.

1. **Set project and asset**
  ```bash
$ mb.bat
$ hulk assets
$ Bruce
```
2. **Query environment**
  ```bash
$ set MINDBENDER_
MINDBENDER_ASSET=Bruce
MINDBENDER_ASSETPATH=C:\Users\marcus\mindbender-example\projects\hulk\assets\Bruce
MINDBENDER_CORE=C:\Users\marcus\mindbender-core
MINDBENDER_EXAMPLE=C:\Users\marcus\mindbender-example\projects
MINDBENDER_FPS=25
MINDBENDER_PROJECT=hulk
MINDBENDER_PROJECTPATH=C:\Users\marcus\mindbender-example\projects\hulk
MINDBENDER_RESOLUTION_HEIGHT=1080
MINDBENDER_RESOLUTION_WIDTH=1920
MINDBENDER_ROOT=C:\Users\marcus\mindbender-example\projects\hulk
MINDBENDER_SILO=assets
```

And there you have it. If you were to manually set these and then launch an application, you'd be doing what `mb.bat` is doing, and what the [Launcher](https://github.com/mindbender-studio/launcher) will be doing.

```bash
$ set MINDBENDER_ASSET=Bruce
$ set MINDBENDER_ASSETPATH=C:\Users\marcus\mindbender-example\projects\hulk\assets\Bruce
...
$ c:\program files\autodesk\maya2016\bin\maya.exe
```

**Comment by mottosso** [comment]
Feel free to re-open this is you encounter any other issues with this.
