### ISSUE TITLE
_mkproject.bat bad help

### ISSUE THREAD

**Issue by mottosso** [mindbender-studio/core#9]
### Problem

The help text for `_mkproject.bat` says the wrong thing, if the project name includes a subdirectory.

```bash
MEINDBENDER START ---------------------------


                _,--,
             .-'---./_    __
            /o \\     '-.' /
            \  //    _.-'._\
             `"\)--"`


  Welcome marcus!

  1. Type first characters of a project, e.g. "p999_"
  2. Press TAB to cycle through matching projects

 ---------------------------------------------

$ p999_Meindbender_Sync
 Uh oh..
   Specify either "assets" or "film"

 Example:
   $ p999_Meindbender_Sync\f02_prod assets
   $ p999_Meindbender_Sync\f02_prod film

$
```

This line...

```bash
   $ p999_Meindbender_Sync\f02_prod assets
```

Should be..

```bash
   $ p999_Meindbender_Sync assets
```

The reason is because the project `name` is..

```bash
call _mkproject %~dp0 %~n0\f02_prod %1
```

It includes `f02_prod` in the name.

### Implementation

To fix this, we'll need to strip characters after `\` in the name in `_mkproject.bat`.

- See [here](https://github.com/mindbender-studio/core/blob/6271520f0f447b6fc2c7b7c03430dc778345a847/bin/_mkproject.bat#L74)

**Comment by mottosso** [comment]
Fixed!

**Comment by LegacyID1991** [comment]
although not yet pull requested so might not be fixed ??? 😰

**Comment by mottosso** [comment]
Sorry! Didn't notice.

**Comment by LegacyID1991** [comment]
Implantation suggestion:
[ProjectName.bat](https://github.com/mindbender-studio/core/blob/master/template/ProjectName.bat)
```
call _mkproject %~dp0 %~n0 %1
```
could instead be
```
call _mkproject %~dp0 %~n0\f01_prod %~n0 %1
```
so it becomes
```
call _mkproject arg1 arg2 arg3 arg4
- arg1 = %~dp0 = drive + path to bat file
- arg2 = %~n0\f01_prod = "f01_prod" could be what ever, this argument is for the projectname plus extra path
- arg3 = %~n0 = Name of the project, just as before the bat name
- arg4 = %1 = silo, same as before
```

Files needed to alter:
[ProjectName.bat](https://github.com/mindbender-studio/core/blob/master/template/ProjectName.bat)
[_mk_projects.bat](https://github.com/mindbender-studio/core/blob/master/bin/_mkproject.bat)

**Comment by mottosso** [comment]
That's an option, but we really shouldn't embed things this specific in the .bat files. It would mean we would be stuck with `f01_prod` forever and ever. If we sometime in the future decide to change the name or not have this folder, we would have to break every other project using it.

Let's take a step back and think about the problem. The problem is that printing the project name includes any additional folders we add to it. So how about simply removing those before printing?

In Python, that would look something like this.

```python
project = "some_project_name/f01_prod".strip("/")
print(project)
```

If we find a way to do that in a .bat file, we'd wouldn't have to change the argument signature between .bat files and safeguard future changes.

**Comment by LegacyID1991** [comment]
I thought this option would actully make us less dependant off `f01_prod`.
This way the name of the project could still be the name of the bat file but the file path is compleatly governed by `arg1 `and `arg2`

We would need to change all of the bat files currently in _f01_projects_ 
but that is a simple task

**Comment by mottosso** [comment]
I've been thinking of how to best explain my objections to this approach and I think I've narrowed it down to this.

The challenge in software design is not so much solving the immediate problem in front of us, but solving it in such a way that it doesn't create new problems down the line. To think ahead and spot errors before they occur.

This approach does work. It does solve the problem. But, it may do so by creating new problems.

The first problem is our future selves looking at..

```bash
call _mkproject %~dp0 %~n0\f01_prod %~n0 %1
```

And asking "Why are there two `%~n0` variables?"

The second problem is when/if you one day decide not to have a subfolder there. To not have `f01_prod`. Which to me is a real option and frankly I can't see a reason to have it in the first place.

At that point, the command would instead look like this.

```bash
call _mkproject %~dp0 %~n0 %~n0 %1
```

Which again would raise the question, more strongly this time "Why is there two `%~n0` variables?". Except this time, someone looking at this string might think that the author has made a mistake, and attempt to remove one of the `%~n0` arguments, thus breaking the file.

Does that make sense?

If we instead solve it in the printing mechanism, by removing anything followed by a `/`, we could maintain the minimal version of what we have *and* have an accurate help message.

**Comment by LegacyID1991** [comment]
I see your point.

but picture this.
While we right now don't see the reason to have a differently named project folder (bat file name is always project folder name.)
I can see this being a way to in the future having bat files that has longer more descriptive names. and then have smarter shorter names underneath the hood, example just having p### and nothing else.

Right now we try to limit the characters as to not go into the windows limit, while still trying to give the artist as much description for them to an easily navigate to the project they are working on.

With the mindbender launcher there is no reason to navigate to the project through a file explorer and there fore the project folders can have much shorter and smarter names. This could also work into a index system later on with project folders not even being acronyms just characters.

But the solution also work with our current setup, just using the bat file name is fine for now.
the solution is aiming for the future, before we have 100 old bat files to edit.

Am I thinking to far ahead and not focusing enough on this current issue ticket ?

**Comment by mottosso** [comment]
Let me see if I got this straight.

- Our common problem is that the help text includes the name of the project + junk we don't want to print, `f01_prod`.
- You want to solve the problem by having two arguments, one with the name + junk and one with just the name.
- I want to solve the problem by passing just name + junk and filter out the junk during printing.

With this in mind, I don't see how the length of project names come into play? The length could be any for both of our suggestions?

**Comment by LegacyID1991** [comment]
That is how I wanna solve this issue Yes.

but the reason that I wanna solve the issue this way is because I was inspired by #25 ..
Thinking that we could have project folders that doesn't need to have the entire bat file name.

**Comment by LegacyID1991** [comment]
instead of 
**p200_client_somenewfilm_2035.bat**
```call _mkproject %~dp0 %~n0\f01_prod %1 ```
*\\...projects\p200_client_somenewfilm_2035\f01_prod\\...*

and instead of
**p300_client_somenewfilm_2045.bat**
```call _mkproject %~dp0 %~n0\f01_prod %~n0 %1```
*\\...projects\p300_client_somenewfilm_2045\f01_prod\\...*

it could be:
**p400_client_somenewfilm_2055.bat**
```call _mkproject %~dp0 p400 %~n0 %1```
*\\...projects\p400\\...*

maybe I am thinking of this the wrong way.
but this would solve the issue and it will create this solution which doesn't have to be used this way but it can be used this way..

**Comment by mottosso** [comment]
Ok, let's do it your way. If you mock this up and submit a PR we can get into testing this.

**Comment by LegacyID1991** [comment]
can we merge this #51 PR first ?

**Comment by mottosso** [comment]
Done
