### ISSUE TITLE
wrong folders and ignoring computer name!

### ISSUE THREAD

**Issue by Stonegrund** [mindbender-studio/core#97]
The issue is apparently project specific, on one of the projects when I have navigated and opened ex. `maya lookdev` and then I open a saved file it looks for `\assets\cat\publish\modelDefault` and not `\f02_prod\assets\cat\publish\modelDefault`. It somehow jumps the `\f02_prod`

And on another project it started to skip computer name, instead of `\work\lookdev\TARS\maya` it maps like this `\work\lookdev\maya`

I have tried on other computers. And restarting both the mb-dev.bat and the computer but still the same issue.

**Comment by Stonegrund** [comment]
![2017-04-05 10_33_55-autodesk maya 2016_ untitled_](https://cloud.githubusercontent.com/assets/22002943/24697767/a30f9c56-19ee-11e7-8328-94d78a993a73.png)

**Comment by Stonegrund** [comment]
Ok, so the creation of computer name in `work\lookdev\` seems to work on mb.bat but not in mb-dev.bat. But the issue with the reference loader not looking in `\f02_prod\assets\` but instead in '\assets\' directly is still apparent.

**Comment by mottosso** [comment]
`mb-dev` is @LegacyID1991 area. Ping!

**Comment by Stonegrund** [comment]
but same issue in `mb.bat`

**Comment by mottosso** [comment]
But what is the issue?

1. The "Reference file not found" seem unrelated; the pipeline has no influence over paths in saved Maya files. That seems like a case of someone simply having moved files around.
2. The exclusion of your computer name is new and intended, speak to Arvid about that.
3. The exclusion of `f02_prod` is indeed project specific and sounds like the project `.bat` file needs updating.

**Comment by Stonegrund** [comment]
This was working just fine. But something while working on a project I needed to reopen a saved file and it gave me first an error in the bat view after typing `theProject assets` saying the path didn't exist. I closed the bat window and opened a new one and then opened `maya lookdev' then `file->open scene` then *boom* maya now not looking in f02_prod anymore. 

Asked @LegacyID1991 but he hadn't done anything new.

**Comment by mottosso** [comment]
> maya now not looking in f02_prod anymore.

Are you referring to the "Reference file not found" dialog box?

If so, the only explanation is that files have been moved since the file was last referenced. Try browsing to wherever it is now and re-saving.

**Comment by Stonegrund** [comment]
Yes, exactly.

But that is weird. Because when I manually go to \f02_prod\assets... it is there and all fine.

**Comment by Stonegrund** [comment]
well well, it perhaps is Maya funkiness.

**Comment by LegacyID1991** [comment]
I have now checked the bat files
_p101_FoodTheif.bat_
>```
>...
>%~n0\f02_prod
>...
>```
which is correct. when compairing the folder structure:
> **M:\f01_projects\p101_FoodTheif\f02_prod\...**

And there is no alteration to mb.bat or mb-dev.bat when compairing github and server files.

**Comment by mottosso** [comment]
> But that is weird. Because when I manually go to \f02_prod\assets... it is there and all fine.

Judging from your screenshot, the asset was referenced when the asset **was not** in `f02_prod` and later **moved** into `f02_prod`.

Could someone simply have moved the asset into `f02_prod` since you last opened the file?

**Comment by mottosso** [comment]
Feel free to re-open if this is still an issue.
